### ISSUE TITLE
Add Moonraker and OctoPrint printer type selector

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster-client#1216]
When adding or updating a printer, it should be possible to specify whether a printer is of type Moonraker or OctoPrint. I'm envisioning a similar selector like: 
![image](https://github.com/fdm-monster/fdm-monster-client/assets/6005355/6d1a3bf1-5c1c-4adf-9177-599ce27b1a49)
This UI should be already familiar to most users.

## Task description
- [ ] Check feature of server for multi-printer type supports and which printer types
- [ ] Design type selector tiles
- [ ] Make printer dialog multi-stage, users should be able to change the printer type. This moves the dialog to previous step.
- [ ] Creating a printer should start in the first step
- [ ] On printer type update wipe the host and apiKey field
